### ISSUE TITLE
Boundary problem in AbstractEvaluator::evaluate_parallel

### ISSUE THREAD

**Issue by Alf802** [usnistgov/NISTfit#5]
I think there is a bug in AbstractEvaluator::evaluate_parallel() at this line:
auto itEnd = itStart + cs -1;// -1 because iEnd is NON-INCLUSIVE !!!!!!!!!!

There should not be the -1 because the for loop in the f lambda is:
for (auto it = itStart; it != itEnd; ++it) {

As an example, if the chunk size were 10, you would want to evaluate [0:9]. This would be done by looping until the iterator was equal to 10. As it is now, you would increment the iterator until it was equal to 9 (cs - 1), so it only evaluates [0:8].

**Comment by ianhbell** [comment]
I had a very grand vision for the library as you can tell by its name.  Sadly I have moved in other directions with these sorts of model optimization approaches. This is non-C++11 code, so it could be simplified even more to remove this family of off-by-1 indexing errors.

**Comment by Alf802** [comment]
I appreciate the effort you put in to the project. I have been using cminpack for many years but I really wanted something which could be run in parallel. I’ve got NISTfit working for some simple examples and I can see the speed improvements when multi threading is enabled. I’m writing a wrapper to provide a simpler interface specific to the types of problems I expect to use it for. I expect this will be replacing cminpack in my toolbox. Thank you.

**Comment by ianhbell** [comment]
I think I agree with you about this particular bug.
